config/routes.rb
Rails.application.routes.draw do

  #match 'dashboard/review/:id' => 'dashboard#review', :via => :put
  get 'services/book/:service_id/:helper_id' => 'services#book'
  #match 'dashboard/review/:id' => 'dashboard#review', :via => :put
  get 'services/review/:id' => 'services#review' , :as => "services_review"


  get 'dashboard/index'
  get 'dashboard/match'
  get 'dashboard/seekers'
  get 'dashboard/helpers'
  # namespace :dashboard do
  #   resources :seekers
 get 'dashboard/sendmail/:id' => 'dashboard#sendmail', :as => "dashboard_sendmail"
  #
  # end
  get 'static/index'

  # app/config/routes.rb
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :services
  resources :profiles
  #devise_for :users


  root 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @profiles = Profile.where(user_id: current_user)
    #@services = Services.where(task_list: "Babysitting")
    @services = Service.where(seeker_id: current_user)
    @services1 = Service.where(helper_id: current_user)
    #@test =  Service.where(service_type: "Offering Help")

    #query all reviews associated to current user
    @review1 = Service.where(seeker_id: current_user)
    @review2 = @review1.where.not(helper_id: nil)
    @review = @review2.where("date_when_seek_help < ?", Date.today )
    render layout: "dashboard"
  end

  def seekers
    if params[:search]
      #Find all record with service_type = "Seeking Help" and task_list meets the search string
      @seeking = Service.where(service_type: "Seeking Help")
      @search = @seeking.where("task_list ilike ?", "%#{params[:search]}%")
    else
      # if search string is empty
      @search = Service.where(service_type: "Seeking Help")
    end
    render layout: "seekers"
  end

  def helpers
    if params[:search]
      #Find all record with service_type = "Seeking Help" and task_list meets the search string
      @User = User.all
      @seeking = Service.where(service_type: "Offering Help")
      @search = @seeking.where("task_list ilike ?", "%#{params[:search]}%")
    else
      # if search string is empty
      @search = Service.where(service_type: "Offering Help")
    end
    render layout: "helpers"
  end

  def sendmail
    #@user = User.find(params[:id]
    # UserMailer.notify(@user).deliver
    # flash[:success] = "Email sent. Helper has been notified"
    # redirect_to dashboard_index_path
    respond_to do |format|
      format.html { redirect_to dashboard_index_path, notice: "Email sent. Helper has been notified"}
    end

  end

  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:id, :seeker_id, :review_for_helper, :rating_for_helper, :review_for_seeker, :rating_for_seeker, :helper_id, :date_when_seek_help, :service_type, task_list:[])
    end


end

app/helpers/dashboard_helper.rb
module DashboardHelper

end

app/views/dashboard/_helpers.html.erb
<div class="dashboard-helpers-wrapper">
  <div class="col-md-12">
    <h3>Helpers Available</h3>
      <%= form_tag dashboard_helpers_path, :method => 'get', :id => "service_search"  do %>
      <%= text_field_tag :search, params[:search]%>
      <%= submit_tag "Search", :name => nil  %>
      <% end %>
      <br />
<table class="table table-hover">
  <thead>
    <tr>
      <th>Category</th>
      <th>Date</th>
      <th>Type</th>
    </tr>
  </thead>
  <tbody>
    <% @search.each do |service| %>
      <tr>
        <td><%= service.task_list %></td>
        <td><%= service.date_when_seek_help %></td>
        <td><%= service.service_type %></td>
        <td><%= service.helper_id %></td>
        <td><%= link_to 'Contact', dashboard_sendmail_path(:id => service.helper_id), class:"btn btn-sm btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/dashboard/_seekers.html.erb
<div class=dashboard-seekers-wrapper>
  <div class="col-md-12">
    <h3>Seeking Help</h3>
      <%= form_tag dashboard_seekers_path, :method => 'get', :id => "service_search"  do %>
      <%= text_field_tag :search, params[:search]%>
      <%= submit_tag "Search", :name => nil  %>
      <% end %>
      <br />
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Category</th>
            <th>Date</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody>
          <% @search.each do |service| %>
          <tr>
            <td><%= service.task_list %></td>
            <td><%= service.date_when_seek_help %></td>
            <td><%= service.service_type %></td>
            <td><%= link_to 'Contact', service, class:"btn btn-sm btn-info" %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/dashboard/helpers.html.erb
<% if user_signed_in? %>
  <div id="helpers"><%= render 'helpers' %></div>
<%else %>
  <p>Please Sign Up or Sign In to view the content.</p>

  <h2><%= link_to "Sign up", new_user_registration_path%>

<% end %>

app/views/dashboard/helpers.js.erb
$("#helpers").html("<%= escape_javascript(render("helpers")) %>")

app/views/dashboard/index.html.erb
<% if user_signed_in? %>
  <div class="dashboard-container">
    <section="dashboard-profile">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6">
            <div class="dashboard-avatar">
              <% @profiles.each do |profile| %>
                  <%= image_tag profile.avatar_url(:display) %>
              <% end %>
            </div>
          </div>
        <div class="dashboard-profile-wrapper">
          <div class="col-md-6">
            <table class="table profile table-hover table-bordered">
              <h3>Profile</h3>
              <% @profiles.each do |profile| %>
              <tbody>
                <tr>
                  <th class="profile">Name</th>
                  <td><%=profile.name%></td>
                </tr>
                <tr>
                  <th class="profile">Contact</th>
                  <td><%=profile.contact%></td>
                </tr>
                <tr>
                  <th class="profile">Address</th>
                  <td><%=profile.address%></td>
                </tr>
              </tbody>
            </table>
            <%= link_to 'Edit', edit_profile_path(profile), class:"btn btn-sm btn-success dashboard-button" %>
            <%= link_to new_service_path, class: "btn btn-sm btn-default" do %>
              <span class="glyphicon glyphicon-save"></span>
            New Service
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    </section>
    <br />
    <section="dashboard-services-reviews">
    <div class="dashboard-reviews-wrapper">
      <div class="container-fluid">
        <div class="col-md-12">
          <table class="table services-reviews table-hover table-bordered">
            <h3>Reviews</h3>
            <thead>
              <tr>
                <th>Service ID</th>
                <th>Service Date</th>
                <th>Helper ID</th>
                <th>Rating</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @review.each do |service| %>
              <tr>
                <td><%= service.id%></td>
                <td><%= service.date_when_seek_help %></td>
                <td><%= service.helper_id %></td>
                <td><%= service.rating_for_helper%></td>
                <td><%= link_to 'View', services_review_path(service.id), class:"btn btn-sm btn-info dashboard-button" %></td>
                <!-- <td><%= link_to 'Remove', service, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger" %></td> -->
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    </section>
    <br />
    <section="dashboard-services-requested">
    <div class="dashboard-requests-wrapper">
      <div class="container-fluid">
        <div class="col-md-12">
          <table class="table services-requested table-hover table-bordered">
            <h3>Services Requested</h3>
            <thead>
              <tr>
                <th>Types of Services Needed</th>
                <th>Date</th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @services.each do |service| %>
              <tr>
                <td><%= service.task_list %></td>
                <td><%= service.date_when_seek_help %></td>
                <td><%= link_to 'Match', service, class:"btn btn-sm btn-info dashboard-button" %></td>
                <td><%= link_to 'Edit', edit_service_path(service), class:"btn btn-sm btn-success dashboard-button" %></td>
                <td><%= link_to 'Delete', service, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger dashboard-button" %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    </section>
    <section="dashboard-services-offered">
    <div class="dashboard-offers-wrapper">
      <div class="container-fluid">
        <div class="col-md-12">
          <table class="table services-offered table-hover table-bordered">
            <h3>Services Offered</h3>
            <thead>
              <tr>
                <th>Types of Services Offered</th>
                <th>Date</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @services1.each do |service| %>
              <tr>
                <td><%= service.task_list %></td>
                <td><%= service.date_when_seek_help %></td>
                <td><%= link_to 'Edit', edit_service_path(service), class:"btn btn-sm btn-success dashboard-button" %></td>
                <td><%= link_to 'Delete', service, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger dashboard-button" %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </section>
  </div>
  </div>
<%else %>
  <p>Please Sign Up or Sign In to view the content.</p>
  <h2><%= link_to "Sign up", new_user_registration_path%>
<% end %>

app/views/dashboard/match.html.erb
<div class="gridly">
  <div class="brick small"></div>
  <div class="brick small"></div>
  <div class="brick large"></div>
  <div class="brick small"></div>
  <div class="brick small"></div>
  <div class="brick large"></div>
</div>

app/views/dashboard/seekers.html.erb
<% if user_signed_in? %>
<div id="seekers"><%= render 'seekers' %></div>
<%else %>
  <p>Please Sign Up or Sign In to view the content.</p>

  <h2><%= link_to "Sign up", new_user_registration_path%>

<% end %>

app/views/dashboard/seekers.js.erb
$("#seekers").html("<%= escape_javascript(render("seekers")) %>")