config/routes.rb
Rails.application.routes.draw do

  #match 'dashboard/review/:id' => 'dashboard#review', :via => :put
  get 'services/book/:service_id/:helper_id' => 'services#book'
  #match 'dashboard/review/:id' => 'dashboard#review', :via => :put
  get 'services/review/:id' => 'services#review' , :as => "services_review"


  get 'dashboard/index'
  get 'dashboard/match'
  get 'dashboard/seekers'
  get 'dashboard/helpers'
  # namespace :dashboard do
  #   resources :seekers
 get 'dashboard/sendmail/:id' => 'dashboard#sendmail', :as => "dashboard_sendmail"
  #
  # end
  get 'static/index'

  # app/config/routes.rb
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :services
  resources :profiles
  #devise_for :users


  root 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord

  mount_uploader :avatar, AvatarUploader

  belongs_to :user

  end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to dashboard_index_url, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to dashboard_index_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :name, :contact, :address, :gender, :avatar)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="profiles-new-form">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <br />
        <section>

            <div class="form-group">
              <%= form.label :name, 'Name' %>
              <%= form.text_field :name, id: :profile_name %>
            </div>
            <div class="form-group">
              <%= form.label :contact, 'Contact' %>
              <%= form.number_field :contact, id: :profile_contact %>
            </div>
            <div class="form-group">
              <%= form.label :address, 'Address' %>
              <%= form.text_field :address, id: :profile_address %>
            </div>
            <div class="form-group">
              <%= form.label :gender, 'Gender' %>
              <%= form.text_field :gender, id: :profile_gender %>
            </div>
            <div class="form-group">
              <legend>Avatar</legend>
              <% unless @profile.avatar_url.nil? %><%= image_tag @profile.avatar_url(:display) %><br /><% end %>
              <%= form.file_field :avatar %>
            </div>
        </section>
      </div>
    </div>
  </div>
</div>

<div class="profiles-form-update-button">
  <%= form.submit class: "btn btn-success" %>
</div>

<% end %>

app/views/profiles/edit.html.erb
<%= render 'form', profile: @profile %>
<%= link_to 'Back', dashboard_index_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="profile-title">
  <h1>Profiles</h1>
</div>
<div class="container profile_table">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Name</th>
      <th>Contact</th>
      <th>Address</th>
      <th>Gender</th>
      <th>Select Options</th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= image_tag profile.avatar_url(:display), :class=>"avatar_picture" %></td>
        <td><%= profile.name %></td>
        <td><%= profile.contact %></td>
        <td><%= profile.address %></td>
        <td><%= profile.gender %></td>
        <td>
        <button type="button" class="btn btn-default btn-xs"><%= link_to 'Show', profile %></button>
        <button type="button" class="btn btn-default btn-xs"><%= link_to 'Edit', edit_profile_path(profile) %></button>
        <button type="button" class="btn btn-default btn-xs"><%= link_to 'Delete', profile, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= link_to new_profile_path, class: "btn btn-default" do %>
  <span class="glyphicon glyphicon-save"></span>
New Profile
<% end %>

app/views/profiles/new.html.erb
<%= render 'form', profile: @profile %>
<%= link_to 'Back', dashboard_index_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @profile.contact %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>

<p>
  <% unless @profile.avatar_url.nil? %><%= image_tag @profile.avatar_url(:display) %><br /><% end %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>